use zcode_cli_core_api as contract;
use zcode_cli_domain as domain;
mod agent_profiles;
pub mod bash_git_safety;
mod checkpoint_blobs;
mod edit_apply;
mod edit_match;
mod edit_quotes;
mod embedded_search;
mod extension_config;
mod extension_plugins;
mod file_changes;
mod file_checkpoints;
mod file_rewind;
mod mcp_config;
mod mcp_connection;
mod mcp_hub;
mod mcp_sse;
mod plan_tools;
#[cfg(unix)]
mod process_tree;
mod shell_select;
mod tool_files;
mod tool_process;
mod tool_search;
mod tool_shell;
mod tool_skills;
mod tool_surface;
pub mod tools;
#[cfg(windows)]
mod win_job;
pub use tools::WorkspaceTools;
use zcode_cli_host::{id, now};
