pub use zcode_cli_protocol as protocol;

pub mod agent_description;
pub mod agent_profile;
pub mod attachment_upload;
pub mod background;
mod bash_callbacks;
mod bash_callbacks_git;
mod bash_callbacks_system;
mod bash_lex;
mod bash_lex_quote;
pub mod bash_model_content;
pub mod bash_parse;
pub mod bash_policy;
mod bash_policy_argv;
mod bash_policy_git;
pub mod bash_rule_policy;
mod bash_rule_prefix;
pub mod builtin_prompt_command;
pub mod context;
pub mod cron;
mod cron_input;
pub mod custom_command;
mod custom_command_template;
pub mod delta_log;
pub mod file_checkpoint;
pub mod goal;
pub mod history;
pub mod json_order;
mod json_size;
pub mod legacy_snapshot;
pub mod mcp_oauth;
pub mod mcp_official_auth;
mod mcp_oauth_pair;
pub mod mcp_cua;
pub mod mcp_result;
pub mod memory;
mod memory_markdown;
mod memory_policy;
mod memory_stamp;
#[cfg(test)]
mod memory_tests;
mod memory_yaml;
pub mod model;
pub mod net_proxy;
pub mod option_map;
pub mod permission;
pub mod permission_options;
mod permission_rules;
pub mod plan_mode;
pub mod prompt;
pub mod question;
mod question_answer;
pub mod rewind_branch;
pub mod runtime_env;
pub mod row_page;
pub mod session;
pub mod session_context;
mod session_context_lite;
mod session_context_parts;
mod session_context_rust;
mod session_context_text;
pub mod session_listing;
mod session_memory;
mod session_recovery;
pub use session_recovery::ToolResult;
pub mod session_title;
#[cfg(test)]
mod session_title_tests;
pub mod shared_context;
pub mod shared_import;
pub mod skills;
pub mod subagent;
mod subagent_row;
pub mod browser_ambient;
pub mod todo;
pub mod tool_display;
pub mod web_fetch;
pub mod web_search;
mod web_fetch_ip;

pub const MAX_REQUEST_BYTES: usize = 1024 * 1024;
pub const MAX_TEXT_BYTES: usize = 256 * 1024;
pub const MAX_TOOL_BYTES: usize = 64 * 1024;
pub const MAX_QUEUE: usize = 32;
