pub use zcode_cli_protocol as protocol;

pub mod agent_description;
pub mod agent_profile;
pub mod attachment_upload;
pub mod background;
mod bash_callbacks;
mod bash_callbacks_git;
mod bash_callbacks_system;
mod bash_lex;
mod bash_lex_quote;
pub mod bash_parse;
pub mod bash_policy;
mod bash_policy_argv;
mod bash_policy_git;
pub mod bash_rule_policy;
mod bash_rule_prefix;
pub mod builtin_prompt_command;
pub mod context;
pub mod delta_log;
pub mod file_checkpoint;
pub mod goal;
pub mod history;
mod json_size;
pub mod legacy_snapshot;
pub mod model;
pub mod net_proxy;
pub mod option_map;
pub mod permission;
pub mod permission_options;
mod permission_rules;
pub mod plan_mode;
pub mod prompt;
pub mod question;
mod question_answer;
pub mod rewind_branch;
pub mod row_page;
pub mod session;
pub mod session_listing;
mod session_memory;
mod session_recovery;
pub mod shared_context;
pub mod shared_import;
pub mod skills;
pub mod subagent;
mod subagent_row;
pub mod todo;
pub mod web_fetch;
mod web_fetch_ip;

pub const MAX_REQUEST_BYTES: usize = 1024 * 1024;
pub const MAX_TEXT_BYTES: usize = 256 * 1024;
pub const MAX_TOOL_BYTES: usize = 64 * 1024;
pub const MAX_QUEUE: usize = 32;
