//! `Session::new`：新会话的初始状态（从 session.rs 拆出，保持文件在 400 行以内）。
use super::session::{Session, interactive, legacy_mode, queue_mode};
use serde_json::json;

impl Session {
    pub fn new(
        id: String,
        workspace: String,
        provider: String,
        model: String,
        reasoning_level: String,
        epoch: String,
        now: u64,
    ) -> Self {
        Self {
            file_checkpoints: vec![],
            rewind_committed: None,
            history: Default::default(),
            row_highwater: 0,
            history_rewrite: false,
            agent_profile: None,
            children: Default::default(),
            mailbox: vec![],
            plan_followups: vec![],
            goal: None,
            skills: None,
            shared_context: None,
            legacy_shared_context: false,
            workspace_path: None,
            workspace_directory: None,
            trace_id: None,
            todos: vec![],
            todos_updated_at: now,
            prompt_snapshot: None,
            context: Default::default(),
            context_tokens: None,
            compact_instructions: None,
            queued_now: None,
            pending_acks: Default::default(),
            // 修复：原先是只支持 yolo 时的默认值，漏传模式的新会话会直接放行写操作。
            // TS 所有默认都是 build（见 docs/specs/rust-permission-modes.md「默认模式」）。
            mode: legacy_mode(),
            plan_enabled: false,
            parent_id: None,
            task_type: interactive(),
            archived_at: None,
            archived: false,
            listed: true,
            attachments: Default::default(),
            background: Default::default(),
            workflow_notices: vec![],
            workflow_actor: None,
            workflow_runs: None,
            workflow_runs_legacy: None,
            workspace_hook_admission: None,
            id,
            workspace,
            provider,
            model,
            reasoning_level,
            thought_levels: vec![],
            epoch,
            title_seed: None,
            title_attempted: false,
            last_local_date: None,
            title: String::new(),
            title_source: "default".into(),
            seq: 0,
            delta_log: Default::default(),
            revision: 0,
            created_at: now,
            updated_at: now,
            phase: "draft".into(),
            rows: vec![],
            messages: vec![],
            saved_rows: 0,
            resident_bytes: None,
            saved_inputs: 0,
            saved_responses: 0,
            saved_messages: 0,
            checkpoint_at: 0,
            api_retry: None,
            usage: json!({"contextWindow":null,"cumulative":{"inputTokens":0,"outputTokens":0,"cacheReadTokens":0,"cacheWriteTokens":0}}),
            last_error: None,
            last_model_failure: None,
            creation_ack: None,
            pending: vec![],
            queue: vec![],
            auto_drain: true,
            followup_mode: queue_mode(),
            run_id: None,
        }
    }
}
